Implement VehicleScheduleFrame komponenten i netex-parser-java bib.
entur/netex-parser-java pull request #105
Opened 2023-06-20 13:07 UTC by gitpiphub

2023-06-20 20:05 UTC, testower commented on src/main/java/org/entur/netex/loader/parser/VehicleScheduleFrameParser.java
> +    private void parseTypeOfValues(TypesOfValueInFrame_RelStructure typesOfValue) {
This method is not used

2023-06-20 20:06 UTC, testower commented on src/test/java/org/entur/netex/VehicleScheduleFrameTest.java
> +            List<String> journeys = new ArrayList<>();
What is the purpose of the dayTypes and journeys lists? They don't seem to be used in any assertions.

2023-06-20 20:17 UTC, testower requested changes
Have a look at my comments. I'd like to run this through @vpaturet as well who is more familiar with this part of NeTEx

2023-06-20 20:19 UTC, testower commented on src/test/java/org/entur/netex/VehicleScheduleFrameTest.java
> +            List<String> journeys = new ArrayList<>();
The privateCode string is not used either

2023-06-21 05:15 UTC, gitpiphub commented on src/main/java/org/entur/netex/loader/parser/VehicleScheduleFrameParser.java
> +    private void parseTypeOfValues(TypesOfValueInFrame_RelStructure typesOfValue) {
> This method is not used

Fixed

2023-06-21 05:15 UTC, gitpiphub commented on src/test/java/org/entur/netex/VehicleScheduleFrameTest.java
> +            List<String> journeys = new ArrayList<>();
> What is the purpose of the mappedBlocks, dayTypes and journeys lists? They don't seem to be used in any assertions.

Fixed

2023-06-21 05:16 UTC, gitpiphub commented on src/test/java/org/entur/netex/VehicleScheduleFrameTest.java
> +public class VehicleScheduleFrameTest {
> public modifier can be removed

Fixed

2023-06-21 06:24 UTC, testower commented on src/main/java/org/entur/netex/index/api/NetexEntitiesIndex.java
> +    NetexEntityIndex<Block> getBlockIndex();
please add a javadoc here

2023-06-21 06:25 UTC, testower commented on src/main/java/org/entur/netex/index/api/NetexEntitiesIndex.java
> +
empty lines around this is not needed

2023-06-21 06:25 UTC, testower commented on src/main/java/org/entur/netex/index/impl/NetexEntitiesIndexImpl.java
> +
remove empty line

2023-06-21 06:26 UTC, testower commented on src/main/java/org/entur/netex/loader/parser/NetexDocumentParser.java
> +                    netexIndex.getFlexibleStopPlaceIndex()
unexpected indentation on this line and on line 90

2023-06-21 08:11 UTC, vpaturet requested changes

2023-06-21 08:11 UTC, vpaturet commented on src/main/java/org/entur/netex/loader/parser/VehicleScheduleFrameParser.java
> +    private void parseBlocks(BlocksInFrame_RelStructure elements) {
you can move private methods to the end of the class

2023-06-22 05:22 UTC, gitpiphub commented on src/main/java/org/entur/netex/loader/parser/VehicleScheduleFrameParser.java
> +    private void parseBlocks(BlocksInFrame_RelStructure elements) {
fixed

2023-06-22 06:31 UTC, vpaturet approved these changes

2023-06-22 06:32 UTC, merged